id: IC49B3324
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T08:34:20+00:00'
last_modified: '2022-06-07T14:55:44.891738+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9247
  title: ས་སྐྱ་པའི་དཔེ་ཐོ་སྣ་ཚོགས།
  author: ''
  base:
    D82C:
      image_group_id: I1KG9334
      title: ''
      total_pages: 324
      order: 1
      base_file: D82C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
