id: P001750
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9247
  title: ས་སྐྱ་པའི་དཔེ་ཐོ་སྣ་ཚོགས།
  author: ''
  volumes:
    e4314e5301e64aedb352eaf0dc9e2a5c:
      image_group_id: I1KG9334
      title: ''
      volume_number: 1
      total_pages: 324
      base_file: v001.txt
